services:
  rtorrent:
    build:
      context: .
      dockerfile: rtorrent.dockerfile
    restart: always
    volumes:
      - ${storage}:/data/downloads
      - sock:/data
    ports:
      - 6881:6881
      - 49264:49264
    tty: true
#    logging:
#      driver: none

  flood:
    build:
      context: .
      dockerfile: flood.dockerfile
    ports:
      - 3000:3000
    links:
      - rtorrent
    depends_on:
      - rtorrent
    environment:
      - RTORRENT_SOCK=true
      - NODE_ENV=development
      - FLOOD_SECRET=flood
    restart: always
    volumes:
      - ${storage}:/data/downloads
      - sock:/data

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - 8989:8989
    restart: always

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - 7878:7878
    restart: always

volumes:
  sock:
